name: 'Repository Vars'
description: 'GitHub action than retrieves all metadata from your repository and uses like env vars'
author: 'luisfalconmx'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'book'
  color: 'gray-dark'

runs:
  using: 'docker'
  image: 'Dockerfile'